tokenizer:
  _target_: bmfm_targets.config.TokenizerConfig
  identifier: all_genes
data_module:
  _target_: bmfm_targets.datasets.cellxgene.CellXGeneNexusDataModule
  _partial_: true
  num_workers: 8
  mlm: true
  collation_strategy: multitask
  shuffle: true
  change_ratio: 0.3
  mask_ratio: 0.95
  max_length: 4096
  sequence_order: random
  switch_ratio: 0.0
  batch_size: 8
  save_state: true
  limit_genes: protein_coding
  rda_transform: downsample
  pad_zero_expression_strategy: batch_wise
  dataset_kwargs:
    uri: /proj/bmfm/omics/data/scRNA/cellxgene/2025-01-30/soma/
    index_dir: /proj/bmfm/omics/data/scRNA/cellxgene/2025-01-30/cellxgene_equal_downsample_1pct_nexus_index/
    expose_zeros: all
    raw_counts: true
label_columns:
- _target_: bmfm_targets.config.LabelColumnInfo
  label_column_name: cell_type
  silent_label_values:
  - unknown
- _target_: bmfm_targets.config.LabelColumnInfo
  label_column_name: tissue
- _target_: bmfm_targets.config.LabelColumnInfo
  label_column_name: tissue_general
- _target_: bmfm_targets.config.LabelColumnInfo
  label_column_name: donor_id
  gradient_reversal_coefficient: 1.5
  silent_label_values:
  - control
fields:
- _target_: bmfm_targets.config.FieldInfo
  field_name: genes
- _target_: bmfm_targets.config.FieldInfo
  field_name: expressions
  is_masked: true
  tokenization_strategy: continuous_value_encoder
  encoder_kwargs:
    kind: scale_adapt
    n_sin_basis: 48
    basis_scale: 1.5
    trainable: true
    zero_as_special_token: true
  decode_modes:
    - regression
    - is_zero
- _target_: bmfm_targets.config.FieldInfo
  field_name: label_expressions
  is_input: false
  is_masked: false
  tokenization_strategy: continuous_value_encoder
task:
  _target_: bmfm_targets.config.TrainingTaskConfig
  default_root_dir: ${oc.env:BMFM_TARGETS_TRAINING_DIR}/1pct_equal_downsample_scale_adapt_rda_only_v2/
  max_epochs: 20
  precision: 16-mixed
  val_check_interval: 4000
  gradient_clip_val: 0.5
  accelerator: gpu
  max_steps: -1
  tf32_mode: medium
  accumulate_grad_batches: 4
  freeze_layers: false
  resume_training_from_ckpt: true
  checkpoints_every_n_train_steps: 10000
  limit_val_batches: 1200
trainer:
  _target_: bmfm_targets.config.TrainerConfig
  warmup_steps: 1000
  weight_decay: 0.01
  learning_rate: 0.0001
  betas:
  - 0.9
  - 0.99
  epsilon: 1.0e-08
  lr_decay_steps: null
  losses:
  - field_name: expressions
    name: mse
    ignore_zero: true
  - field_name: expressions
    name: is_zero_bce
  batch_prediction_behavior: track
model:
  _target_: bmfm_targets.config.SCBertConfig
  _partial_: true
  num_hidden_layers: 12
  num_attention_heads: 12
  intermediate_size: 3072
  hidden_act: gelu
  hidden_size: 768
  hidden_dropout_prob: 0.1
  attention_probs_dropout_prob: 0.1
  initializer_range: 0.02
  layer_norm_eps: 1.0e-12
  use_cache: true
  attention: torch
  checkpoint: null
track_clearml:
  project_name: bmfm-targets
  task_name: mlm.rda.v1
  continue_last_task: true
seed:
  seed_value: 1234
