defaults:
  - task: predict
  - data_module: dna_base_seq_cls
  - label_columns: dnaeval_default
  - trainer: default
  - _self_

seed:
  seed_value: 1234

data_module:
  shuffle: false
  collation_strategy: language_modeling
  dataset_kwargs:
    processed_data_source: "${input_directory}/${input_filename}"
    dataset_name: ${dataset_name}
    label_dict_path: "${input_directory}/{dataset_name}_all_labels.json"

task:
  output_embeddings: true
  output_predictions: true
  default_root_dir: ${working_dir}


trainer:
  losses:
    - name: cross_entropy
      label_column_name: ${label_columns[0].label_column_name}



accelerator: gpu
input_filename: ""
working_dir: /tmp
checkpoint: null

batch_size: 32
dataset_name: coreprom
label_column_name: label
input_directory: /proj/bmfm/datasets/omics/genome/finetune_datasets/core_promoter_prediction/
